from sqlalchemy.orm import DeclarativeBase


# Basically this wrapper allows the Metadata object to be autogenerated for env.py
# Needed to use DeclarativeBase at all
# See https://docs.sqlalchemy.org/en/21/orm/extensions/declarative/index.html#declarative-toplevel
class Base(DeclarativeBase):
    pass
