"""update for evan

Revision ID: 023eaa79cde6
Revises: 1f955c767c7e
Create Date: 2026-03-02 11:59:27.443821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023eaa79cde6'
down_revision: Union[str, Sequence[str], None] = '1f955c767c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('prep_time_minutes', sa.Integer(), nullable=False))
    op.add_column('schedules', sa.Column('recipe_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('target_weight', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('target_body_fat', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('target_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('wake_up_time', sa.Time(), nullable=True))
    op.add_column('user', sa.Column('sleep_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sleep_time')
    op.drop_column('user', 'wake_up_time')
    op.drop_column('user', 'target_date')
    op.drop_column('user', 'target_body_fat')
    op.drop_column('user', 'target_weight')
    op.drop_column('schedules', 'recipe_id')
    op.drop_column('schedules', 'prep_time_minutes')
    # ### end Alembic commands ###
