"""dietary stuff

Revision ID: 1f955c767c7e
Revises: 7314ef4e6209
Create Date: 2026-02-24 13:15:31.529135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f955c767c7e'
down_revision: Union[str, Sequence[str], None] = '7314ef4e6209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_allergies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('value', sa.Enum('DAIRY', 'EGG', 'GLUTEN', 'GRAIN', 'PEANUT', 'SEAFOOD', 'SESAME', 'SHELLFISH', 'SOY', 'SULFITE', 'TREE_NUT', 'WHEAT', name='allergy_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_allergies_id'), 'user_allergies', ['id'], unique=False)
    op.create_table('user_exclude_cuisines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('value', sa.Enum('AFRICAN', 'ASIAN', 'AMERICAN', 'BRITISH', 'CAJUN', 'CARIBBEAN', 'CHINESE', 'EASTERN_EUROPEAN', 'EUROPEAN', 'FRENCH', 'GERMAN', 'GREEK', 'INDIAN', 'IRISH', 'ITALIAN', 'JAPANESE', 'JEWISH', 'KOREAN', 'LATIN_AMERICAN', 'MEDITERRANEAN', 'MEXICAN', 'MIDDLE_EASTERN', 'NORDIC', 'SOUTHERN', 'SPANISH', 'THAI', 'VIETNAMESE', name='cuisine_exclude_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_exclude_cuisines_id'), 'user_exclude_cuisines', ['id'], unique=False)
    op.create_table('user_include_cuisines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('value', sa.Enum('AFRICAN', 'ASIAN', 'AMERICAN', 'BRITISH', 'CAJUN', 'CARIBBEAN', 'CHINESE', 'EASTERN_EUROPEAN', 'EUROPEAN', 'FRENCH', 'GERMAN', 'GREEK', 'INDIAN', 'IRISH', 'ITALIAN', 'JAPANESE', 'JEWISH', 'KOREAN', 'LATIN_AMERICAN', 'MEDITERRANEAN', 'MEXICAN', 'MIDDLE_EASTERN', 'NORDIC', 'SOUTHERN', 'SPANISH', 'THAI', 'VIETNAMESE', name='cuisine_include_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_include_cuisines_id'), 'user_include_cuisines', ['id'], unique=False)
    op.drop_column('user', 'include_cuisine')
    op.drop_column('user', 'exclude_cuisine')
    op.drop_column('user', 'allergies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Re-add the JSON columns with a temporary server_default so existing rows
    # backfill to '[]' and don't violate NOT NULL, then strip the default to
    # match the original schema (which had no default).
    op.add_column('user', sa.Column('allergies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, server_default=sa.text("'[]'::json")))
    op.add_column('user', sa.Column('exclude_cuisine', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, server_default=sa.text("'[]'::json")))
    op.add_column('user', sa.Column('include_cuisine', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, server_default=sa.text("'[]'::json")))
    op.alter_column('user', 'allergies', server_default=None)
    op.alter_column('user', 'exclude_cuisine', server_default=None)
    op.alter_column('user', 'include_cuisine', server_default=None)
    op.drop_index(op.f('ix_user_include_cuisines_id'), table_name='user_include_cuisines')
    op.drop_table('user_include_cuisines')
    op.drop_index(op.f('ix_user_exclude_cuisines_id'), table_name='user_exclude_cuisines')
    op.drop_table('user_exclude_cuisines')
    op.drop_index(op.f('ix_user_allergies_id'), table_name='user_allergies')
    op.drop_table('user_allergies')
    sa.Enum(name='allergy_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='cuisine_exclude_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='cuisine_include_enum').drop(op.get_bind(), checkfirst=True)
