"""Initial migration

Revision ID: 51db8ff87aba
Revises: 
Create Date: 2026-02-17 16:22:46.652368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51db8ff87aba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('show_imperial', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='sex_enum'), nullable=False),
    sa.Column('activity_level', sa.Enum('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE', name='activity_level_enum'), nullable=False),
    sa.Column('pregnancy_status', sa.Enum('NOT_PREGNANT', 'PREGNANT', 'EXCLUSIVELY_BREASTFEEDING', 'PARTIALLY_BREASTFEEDING', name='pregnancy_status_enum'), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('include_cuisine', sa.JSON(), nullable=False),
    sa.Column('exclude_cuisine', sa.JSON(), nullable=False),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=False),
    sa.Column('is_ketogenic', sa.Boolean(), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('is_pescatarian', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
