"""Refactored meal to be under a schedule item

Revision ID: 6ea868ba6f73
Revises: a1b2c3d4e5f6
Create Date: 2026-04-18 17:59:53.954275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ea868ba6f73'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=False),
    sa.Column('carbohydrates', sa.Integer(), nullable=False),
    sa.Column('fat', sa.Integer(), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_id'), 'meals', ['id'], unique=False)
    op.create_index(op.f('ix_meals_recipe_id'), 'meals', ['recipe_id'], unique=False)
    op.create_table('schedule_item_alternatives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_item_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_item_alternatives_schedule_item_id'), 'schedule_item_alternatives', ['schedule_item_id'], unique=False)
    op.drop_index(op.f('ix_saved_meal_plans_id'), table_name='saved_meal_plans')
    op.drop_table('saved_meal_plans')
    op.add_column('schedules', sa.Column('meal_id', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('source_schedule_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedules', 'meals', ['meal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'schedules', 'schedules', ['source_schedule_item_id'], ['id'], ondelete='SET NULL')
    op.drop_column('schedules', 'recipe_id')
    op.alter_column('user', 'target_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'target_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('schedules', sa.Column('recipe_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'source_schedule_item_id')
    op.drop_column('schedules', 'meal_id')
    op.create_table('saved_meal_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('week_start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('plan_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('saved_meal_plans_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('saved_meal_plans_pkey')),
    sa.UniqueConstraint('user_id', 'week_start_date', name=op.f('saved_meal_plans_user_id_week_start_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_saved_meal_plans_id'), 'saved_meal_plans', ['id'], unique=False)
    op.drop_index(op.f('ix_schedule_item_alternatives_schedule_item_id'), table_name='schedule_item_alternatives')
    op.drop_table('schedule_item_alternatives')
    op.drop_index(op.f('ix_meals_recipe_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_id'), table_name='meals')
    op.drop_table('meals')
    # ### end Alembic commands ###
