"""refactor goals to separate table

Revision ID: 89987c2b6f2a
Revises: c2be6da47bc6
Create Date: 2026-01-21 21:53:16.623288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89987c2b6f2a'
down_revision: Union[str, Sequence[str], None] = 'c2be6da47bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usergoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('target_value', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usergoal_id'), 'usergoal', ['id'], unique=False)
    op.create_index(op.f('ix_usergoal_user_id'), 'usergoal', ['user_id'], unique=False)
    op.drop_column('user', 'goals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('goals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_usergoal_user_id'), table_name='usergoal')
    op.drop_index(op.f('ix_usergoal_id'), table_name='usergoal')
    op.drop_table('usergoal')
    # ### end Alembic commands ###
