"""introduce google calendar schema

Revision ID: 8e3bf73c2c0b
Revises: db1bc88ad384
Create Date: 2026-04-26 17:49:16.587826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3bf73c2c0b'
down_revision: Union[str, Sequence[str], None] = 'db1bc88ad384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('google_account_email', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_google_calendar_user')
    )
    op.create_index(op.f('ix_google_calendar_connections_user_id'), 'google_calendar_connections', ['user_id'], unique=False)
    op.add_column(
        'schedules',
        sa.Column(
            'source_type',
            sa.String(),
            nullable=False,
            server_default='sophros',
        ),
    )
    op.add_column('schedules', sa.Column('source_calendar_id', sa.String(), nullable=True))
    op.alter_column('schedules', 'source_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'source_calendar_id')
    op.drop_column('schedules', 'source_type')
    op.drop_index(op.f('ix_google_calendar_connections_user_id'), table_name='google_calendar_connections')
    op.drop_table('google_calendar_connections')
    # ### end Alembic commands ###
