"""Add remaining Exercise notes to DB

Revision ID: db1bc88ad384
Revises: a6d24070f720
Create Date: 2026-04-22 15:15:43.940743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1bc88ad384'
down_revision: Union[str, Sequence[str], None] = 'a6d24070f720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('exercise_calorie_burn', sa.Integer(), nullable=False))
    op.add_column('schedules', sa.Column('exercise_muscle_gain', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'exercise_muscle_gain')
    op.drop_column('schedules', 'exercise_calorie_burn')
    # ### end Alembic commands ###
