// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  CreateScheduleItemApiV1SchedulesPostData,
  CreateScheduleItemApiV1SchedulesPostErrors,
  CreateScheduleItemApiV1SchedulesPostResponses,
  CreateUserApiV1UsersPostData,
  CreateUserApiV1UsersPostErrors,
  CreateUserApiV1UsersPostResponses,
  DeleteScheduleItemApiV1SchedulesItemIdDeleteData,
  DeleteScheduleItemApiV1SchedulesItemIdDeleteErrors,
  DeleteScheduleItemApiV1SchedulesItemIdDeleteResponses,
  GenerateMealPlanApiV1MealPlansGeneratePostData,
  GenerateMealPlanApiV1MealPlansGeneratePostErrors,
  GenerateMealPlanApiV1MealPlansGeneratePostResponses,
  GenerateWeekPlanApiV1MealPlansGenerateWeekPostData,
  GenerateWeekPlanApiV1MealPlansGenerateWeekPostResponses,
  GetPlannedWeeksApiV1MealPlansPlannedWeeksGetData,
  GetPlannedWeeksApiV1MealPlansPlannedWeeksGetResponses,
  GetScheduleItemsApiV1SchedulesGetData,
  GetScheduleItemsApiV1SchedulesGetErrors,
  GetScheduleItemsApiV1SchedulesGetResponses,
  GetWeekPlanApiV1MealPlansWeekGetData,
  GetWeekPlanApiV1MealPlansWeekGetErrors,
  GetWeekPlanApiV1MealPlansWeekGetResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
  ReadUserMeApiV1UsersMeGetData,
  ReadUserMeApiV1UsersMeGetErrors,
  ReadUserMeApiV1UsersMeGetResponses,
  ReadUserTargetsApiV1UsersMeTargetsGetData,
  ReadUserTargetsApiV1UsersMeTargetsGetResponses,
  RootGetData,
  RootGetResponses,
  SaveMealPlanApiV1MealPlansSavePostData,
  SaveMealPlanApiV1MealPlansSavePostErrors,
  SaveMealPlanApiV1MealPlansSavePostResponses,
  UpdateScheduleItemApiV1SchedulesItemIdPutData,
  UpdateScheduleItemApiV1SchedulesItemIdPutErrors,
  UpdateScheduleItemApiV1SchedulesItemIdPutResponses,
  UpdateUserMeApiV1UsersMePutData,
  UpdateUserMeApiV1UsersMePutErrors,
  UpdateUserMeApiV1UsersMePutResponses,
  ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostData,
  ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostErrors,
  ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Create User
 *
 * Create new user.
 * Called by frontend after Clerk signup, or via Webhook (secure).
 */
export const createUserApiV1UsersPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserApiV1UsersPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateUserApiV1UsersPostResponses,
    CreateUserApiV1UsersPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Read User Me
 *
 * Get current user profile.
 */
export const readUserMeApiV1UsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUserMeApiV1UsersMeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ReadUserMeApiV1UsersMeGetResponses,
    ReadUserMeApiV1UsersMeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options,
  });

/**
 * Update User Me
 *
 * Update current user profile.
 * Dietary list fields (allergies, include_cuisine, exclude_cuisine) are
 * replaced wholesale — existing rows are deleted and new ones inserted.
 * Validates busy times against meal windows before saving.
 */
export const updateUserMeApiV1UsersMePut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserMeApiV1UsersMePutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateUserMeApiV1UsersMePutResponses,
    UpdateUserMeApiV1UsersMePutErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Validate Busy Times
 *
 * Validate that busy times don't prevent meal scheduling.
 * Returns list of conflicting meals or success.
 *
 * Call this before updating the user profile to give feedback.
 */
export const validateBusyTimesApiV1UsersMeValidateBusyTimesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostResponses,
    ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me/validate-busy-times',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Read User Targets
 *
 * Get nutrient targets based on user profile.
 */
export const readUserTargetsApiV1UsersMeTargetsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUserTargetsApiV1UsersMeTargetsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ReadUserTargetsApiV1UsersMeTargetsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me/targets',
    ...options,
  });

/**
 * Get Schedule Items
 *
 * Fetch schedule items for the current user within a date range.
 */
export const getScheduleItemsApiV1SchedulesGet = <ThrowOnError extends boolean = false>(
  options: Options<GetScheduleItemsApiV1SchedulesGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetScheduleItemsApiV1SchedulesGetResponses,
    GetScheduleItemsApiV1SchedulesGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/schedules',
    ...options,
  });

/**
 * Create Schedule Item
 *
 * Create a new schedule item for the current user.
 */
export const createScheduleItemApiV1SchedulesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateScheduleItemApiV1SchedulesPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateScheduleItemApiV1SchedulesPostResponses,
    CreateScheduleItemApiV1SchedulesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/schedules',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Schedule Item
 *
 * Delete a schedule item by ID (must belong to the current user).
 */
export const deleteScheduleItemApiV1SchedulesItemIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteScheduleItemApiV1SchedulesItemIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteScheduleItemApiV1SchedulesItemIdDeleteResponses,
    DeleteScheduleItemApiV1SchedulesItemIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/schedules/{item_id}',
    ...options,
  });

/**
 * Update Schedule Item
 *
 * Update a schedule item by ID (must belong to the current user).
 */
export const updateScheduleItemApiV1SchedulesItemIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateScheduleItemApiV1SchedulesItemIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateScheduleItemApiV1SchedulesItemIdPutResponses,
    UpdateScheduleItemApiV1SchedulesItemIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/schedules/{item_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Generate Meal Plan
 *
 * Generate a complete daily meal plan for the current user.
 *
 * Uses:
 * - NutrientCalculator to determine daily targets
 * - MealAllocator to split targets into timed meal slots
 * - SpoonacularClient to fetch suitable recipes
 *
 * Returns a populated DailyMealPlan with recipes for Breakfast, Lunch, Dinner.
 */
export const generateMealPlanApiV1MealPlansGeneratePost = <ThrowOnError extends boolean = false>(
  options?: Options<GenerateMealPlanApiV1MealPlansGeneratePostData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    GenerateMealPlanApiV1MealPlansGeneratePostResponses,
    GenerateMealPlanApiV1MealPlansGeneratePostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/meal-plans/generate',
    ...options,
  });

/**
 * Generate Week Plan
 *
 * Generate a complete weekly meal plan for the current user.
 *
 * Runs all 7 days in parallel via asyncio.gather.
 * Returns a WeeklyMealPlan with recipes for every slot of every day.
 */
export const generateWeekPlanApiV1MealPlansGenerateWeekPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GenerateWeekPlanApiV1MealPlansGenerateWeekPostData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    GenerateWeekPlanApiV1MealPlansGenerateWeekPostResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/meal-plans/generate-week',
    ...options,
  });

/**
 * Save Meal Plan
 *
 * Upsert a confirmed weekly meal plan. week_start_date must be a Monday.
 */
export const saveMealPlanApiV1MealPlansSavePost = <ThrowOnError extends boolean = false>(
  options: Options<SaveMealPlanApiV1MealPlansSavePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SaveMealPlanApiV1MealPlansSavePostResponses,
    SaveMealPlanApiV1MealPlansSavePostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/meal-plans/save',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Week Plan
 *
 * Get a saved meal plan for a specific week, or null if none exists.
 */
export const getWeekPlanApiV1MealPlansWeekGet = <ThrowOnError extends boolean = false>(
  options: Options<GetWeekPlanApiV1MealPlansWeekGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetWeekPlanApiV1MealPlansWeekGetResponses,
    GetWeekPlanApiV1MealPlansWeekGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/meal-plans/week',
    ...options,
  });

/**
 * Get Planned Weeks
 *
 * List all week_start_dates the user has planned.
 */
export const getPlannedWeeksApiV1MealPlansPlannedWeeksGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetPlannedWeeksApiV1MealPlansPlannedWeeksGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetPlannedWeeksApiV1MealPlansPlannedWeeksGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/meal-plans/planned-weeks',
    ...options,
  });

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
    url: '/health',
    ...options,
  });

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(
  options?: Options<RootGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
    url: '/',
    ...options,
  });
