// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ActivityLevel
 */
export type ActivityLevel = 'sedentary' | 'light' | 'moderate' | 'active' | 'very_active';

/**
 * ActivityType
 */
export type ActivityType = 'meal' | 'sleep' | 'work' | 'exercise' | 'leisure' | 'other';

/**
 * Allergy
 */
export type Allergy =
  | 'Dairy'
  | 'Egg'
  | 'Gluten'
  | 'Grain'
  | 'Peanut'
  | 'Seafood'
  | 'Sesame'
  | 'Shellfish'
  | 'Soy'
  | 'Sulfite'
  | 'Tree Nut'
  | 'Wheat';

/**
 * BusyTime
 */
export type BusyTime = {
  day?: Day;
  /**
   * Start
   */
  start?: string;
  /**
   * End
   */
  end?: string;
};

/**
 * BusyTimeValidationResult
 *
 * Result of validating busy times against meal windows.
 */
export type BusyTimeValidationResult = {
  /**
   * Is Valid
   */
  is_valid: boolean;
  /**
   * Conflicting Meals
   *
   * List of meal slots that have no available time windows
   */
  conflicting_meals?: Array<string>;
  /**
   * Message
   */
  message?: string | null;
};

/**
 * Cuisine
 */
export type Cuisine =
  | 'African'
  | 'Asian'
  | 'American'
  | 'British'
  | 'Cajun'
  | 'Caribbean'
  | 'Chinese'
  | 'Eastern European'
  | 'European'
  | 'French'
  | 'German'
  | 'Greek'
  | 'Indian'
  | 'Irish'
  | 'Italian'
  | 'Japanese'
  | 'Jewish'
  | 'Korean'
  | 'Latin American'
  | 'Mediterranean'
  | 'Mexican'
  | 'Middle Eastern'
  | 'Nordic'
  | 'Southern'
  | 'Spanish'
  | 'Thai'
  | 'Vietnamese';

/**
 * DRIOutput
 */
export type DriOutput = {
  calories: NutrientRange;
  protein: NutrientRange;
  carbohydrates: NutrientRange;
  fat: NutrientRange;
};

/**
 * DailyMealPlan
 */
export type DailyMealPlanInput = {
  day: Day;
  /**
   * Slots
   */
  slots: Array<MealSlotTargetInput>;
  exercise?: ExerciseRecommendation | null;
  /**
   * Total Calories
   */
  total_calories: number;
  /**
   * Total Protein
   */
  total_protein: number;
  /**
   * Total Carbs
   */
  total_carbs: number;
  /**
   * Total Fat
   */
  total_fat: number;
};

/**
 * DailyMealPlan
 */
export type DailyMealPlanOutput = {
  day: Day;
  /**
   * Slots
   */
  slots: Array<MealSlotTargetOutput>;
  exercise?: ExerciseRecommendation | null;
  /**
   * Total Calories
   */
  total_calories: number;
  /**
   * Total Protein
   */
  total_protein: number;
  /**
   * Total Carbs
   */
  total_carbs: number;
  /**
   * Total Fat
   */
  total_fat: number;
};

/**
 * Day
 */
export type Day =
  | 'Monday'
  | 'Tuesday'
  | 'Wednesday'
  | 'Thursday'
  | 'Friday'
  | 'Saturday'
  | 'Sunday';

/**
 * ExerciseCategory
 */
export type ExerciseCategory = 'Cardio' | 'Weight Lifting';

/**
 * ExerciseRecommendation
 */
export type ExerciseRecommendation = {
  category: ExerciseCategory;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Time
   */
  time?: string | null;
  /**
   * Calories Burned
   */
  calories_burned?: number;
  /**
   * Muscle Gain Estimate Kg
   */
  muscle_gain_estimate_kg?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * MealOption
 */
export type MealOptionInput = {
  main_recipe?: Recipe | null;
  /**
   * Alternatives
   */
  alternatives?: Array<Recipe>;
};

/**
 * MealOption
 */
export type MealOptionOutput = {
  main_recipe?: Recipe | null;
  /**
   * Alternatives
   */
  alternatives?: Array<Recipe>;
};

/**
 * MealSlot
 */
export type MealSlot = 'Breakfast' | 'Lunch' | 'Dinner';

/**
 * MealSlotTarget
 */
export type MealSlotTargetInput = {
  slot_name: MealSlot;
  /**
   * Calories
   */
  calories: number;
  /**
   * Protein
   */
  protein: number;
  /**
   * Carbohydrates
   */
  carbohydrates: number;
  /**
   * Fat
   */
  fat: number;
  /**
   * Time
   */
  time?: string | null;
  plan?: MealOptionInput | null;
  /**
   * Is Leftover
   */
  is_leftover?: boolean;
  leftover_from_day?: Day | null;
  leftover_from_slot?: MealSlot | null;
  /**
   * Prep Time Minutes
   */
  prep_time_minutes?: number;
};

/**
 * MealSlotTarget
 */
export type MealSlotTargetOutput = {
  slot_name: MealSlot;
  /**
   * Calories
   */
  calories: number;
  /**
   * Protein
   */
  protein: number;
  /**
   * Carbohydrates
   */
  carbohydrates: number;
  /**
   * Fat
   */
  fat: number;
  /**
   * Time
   */
  time?: string | null;
  plan?: MealOptionOutput | null;
  /**
   * Is Leftover
   */
  is_leftover?: boolean;
  leftover_from_day?: Day | null;
  leftover_from_slot?: MealSlot | null;
  /**
   * Prep Time Minutes
   */
  prep_time_minutes?: number;
};

/**
 * NutrientRange
 */
export type NutrientRange = {
  /**
   * Min
   */
  min: number;
  /**
   * Target
   */
  target: number;
  /**
   * Max
   */
  max: number;
  /**
   * Unit
   */
  unit?: string;
};

/**
 * PregnancyStatus
 */
export type PregnancyStatus =
  | 'not_pregnant'
  | 'pregnant'
  | 'exclusively_breastfeeding'
  | 'partially_breastfeeding';

/**
 * Recipe
 */
export type Recipe = {
  /**
   * Id
   */
  id: string;
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  nutrients: RecipeNutrients;
  /**
   * Tags
   */
  tags?: Array<string>;
  /**
   * Ingredients
   */
  ingredients?: Array<string>;
  /**
   * Warnings
   */
  warnings?: Array<string>;
  /**
   * Preparation Time Minutes
   */
  preparation_time_minutes?: number | null;
  /**
   * Source Url
   */
  source_url?: string | null;
  /**
   * Image Url
   */
  image_url?: string | null;
};

/**
 * RecipeNutrients
 */
export type RecipeNutrients = {
  /**
   * Calories
   */
  calories: number;
  /**
   * Protein
   */
  protein: number;
  /**
   * Carbohydrates
   */
  carbohydrates: number;
  /**
   * Fat
   */
  fat: number;
};

/**
 * SaveMealPlanRequest
 */
export type SaveMealPlanRequest = {
  /**
   * Week Start Date
   */
  week_start_date: string;
  plan_data: WeeklyMealPlanInput;
};

/**
 * SavedMealPlanResponse
 */
export type SavedMealPlanResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Week Start Date
   */
  week_start_date: string;
  plan_data: WeeklyMealPlanOutput;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * ScheduleItemCreate
 */
export type ScheduleItemCreate = {
  /**
   * Date
   */
  date: string;
  activity_type: ActivityType;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Is Completed
   */
  is_completed?: boolean;
};

/**
 * ScheduleItemRead
 */
export type ScheduleItemRead = {
  /**
   * Date
   */
  date: string;
  activity_type: ActivityType;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Is Completed
   */
  is_completed?: boolean;
  /**
   * Id
   */
  id: number;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * ScheduleItemUpdate
 */
export type ScheduleItemUpdate = {
  /**
   * Date
   */
  date?: string | null;
  activity_type?: ActivityType | null;
  /**
   * Duration Minutes
   */
  duration_minutes?: number | null;
  /**
   * Is Completed
   */
  is_completed?: boolean | null;
};

/**
 * Sex
 */
export type Sex = 'male' | 'female';

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Age
   */
  age: number;
  /**
   * Weight
   */
  weight: number;
  /**
   * Height
   */
  height: number;
  /**
   * Show Imperial
   */
  show_imperial: boolean;
  gender: Sex;
  activity_level: ActivityLevel;
  pregnancy_status?: PregnancyStatus;
  /**
   * Target Weight
   */
  target_weight?: number | null;
  /**
   * Target Body Fat
   */
  target_body_fat?: number | null;
  /**
   * Target Date
   */
  target_date?: string | null;
  /**
   * Wake Up Time
   */
  wake_up_time?: string;
  /**
   * Sleep Time
   */
  sleep_time?: string;
  /**
   * Busy Times
   */
  busy_times?: Array<BusyTime>;
  /**
   * Allergies
   */
  allergies?: Array<Allergy>;
  /**
   * Include Cuisine
   */
  include_cuisine?: Array<Cuisine>;
  /**
   * Exclude Cuisine
   */
  exclude_cuisine?: Array<Cuisine>;
  /**
   * Is Gluten Free
   */
  is_gluten_free?: boolean;
  /**
   * Is Ketogenic
   */
  is_ketogenic?: boolean;
  /**
   * Is Vegetarian
   */
  is_vegetarian?: boolean;
  /**
   * Is Vegan
   */
  is_vegan?: boolean;
  /**
   * Is Pescatarian
   */
  is_pescatarian?: boolean;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Email
   */
  email: string;
  /**
   * Age
   */
  age: number;
  /**
   * Weight
   */
  weight: number;
  /**
   * Height
   */
  height: number;
  /**
   * Show Imperial
   */
  show_imperial: boolean;
  gender: Sex;
  activity_level: ActivityLevel;
  pregnancy_status?: PregnancyStatus;
  /**
   * Target Weight
   */
  target_weight?: number | null;
  /**
   * Target Body Fat
   */
  target_body_fat?: number | null;
  /**
   * Target Date
   */
  target_date?: string | null;
  /**
   * Wake Up Time
   */
  wake_up_time?: string;
  /**
   * Sleep Time
   */
  sleep_time?: string;
  /**
   * Busy Times
   */
  busy_times?: Array<BusyTime>;
  /**
   * Allergies
   */
  allergies?: Array<Allergy>;
  /**
   * Include Cuisine
   */
  include_cuisine?: Array<Cuisine>;
  /**
   * Exclude Cuisine
   */
  exclude_cuisine?: Array<Cuisine>;
  /**
   * Is Gluten Free
   */
  is_gluten_free?: boolean;
  /**
   * Is Ketogenic
   */
  is_ketogenic?: boolean;
  /**
   * Is Vegetarian
   */
  is_vegetarian?: boolean;
  /**
   * Is Vegan
   */
  is_vegan?: boolean;
  /**
   * Is Pescatarian
   */
  is_pescatarian?: boolean;
  /**
   * Id
   */
  id: string;
  /**
   * Schedules
   */
  schedules?: Array<unknown>;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Email
   */
  email?: string | null;
  /**
   * Age
   */
  age?: number | null;
  /**
   * Weight
   */
  weight?: number | null;
  /**
   * Height
   */
  height?: number | null;
  /**
   * Show Imperial
   */
  show_imperial?: boolean | null;
  gender?: Sex | null;
  activity_level?: ActivityLevel | null;
  pregnancy_status?: PregnancyStatus | null;
  /**
   * Target Weight
   */
  target_weight?: number | null;
  /**
   * Target Body Fat
   */
  target_body_fat?: number | null;
  /**
   * Target Date
   */
  target_date?: string | null;
  /**
   * Wake Up Time
   */
  wake_up_time?: string | null;
  /**
   * Sleep Time
   */
  sleep_time?: string | null;
  /**
   * Busy Times
   */
  busy_times?: Array<BusyTime> | null;
  /**
   * Allergies
   */
  allergies?: Array<Allergy> | null;
  /**
   * Include Cuisine
   */
  include_cuisine?: Array<Cuisine> | null;
  /**
   * Exclude Cuisine
   */
  exclude_cuisine?: Array<Cuisine> | null;
  /**
   * Is Gluten Free
   */
  is_gluten_free?: boolean | null;
  /**
   * Is Ketogenic
   */
  is_ketogenic?: boolean | null;
  /**
   * Is Vegetarian
   */
  is_vegetarian?: boolean | null;
  /**
   * Is Vegan
   */
  is_vegan?: boolean | null;
  /**
   * Is Pescatarian
   */
  is_pescatarian?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * WeeklyMealPlan
 */
export type WeeklyMealPlanInput = {
  /**
   * Daily Plans
   */
  daily_plans: Array<DailyMealPlanInput>;
  /**
   * Total Weekly Calories
   */
  total_weekly_calories: number;
};

/**
 * WeeklyMealPlan
 */
export type WeeklyMealPlanOutput = {
  /**
   * Daily Plans
   */
  daily_plans: Array<DailyMealPlanOutput>;
  /**
   * Total Weekly Calories
   */
  total_weekly_calories: number;
};

export type CreateUserApiV1UsersPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: '/api/v1/users';
};

export type CreateUserApiV1UsersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserApiV1UsersPostError =
  CreateUserApiV1UsersPostErrors[keyof CreateUserApiV1UsersPostErrors];

export type CreateUserApiV1UsersPostResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type CreateUserApiV1UsersPostResponse =
  CreateUserApiV1UsersPostResponses[keyof CreateUserApiV1UsersPostResponses];

export type ReadUserMeApiV1UsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/me';
};

export type ReadUserMeApiV1UsersMeGetErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type ReadUserMeApiV1UsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type ReadUserMeApiV1UsersMeGetResponse =
  ReadUserMeApiV1UsersMeGetResponses[keyof ReadUserMeApiV1UsersMeGetResponses];

export type UpdateUserMeApiV1UsersMePutData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: '/api/v1/users/me';
};

export type UpdateUserMeApiV1UsersMePutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserMeApiV1UsersMePutError =
  UpdateUserMeApiV1UsersMePutErrors[keyof UpdateUserMeApiV1UsersMePutErrors];

export type UpdateUserMeApiV1UsersMePutResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UpdateUserMeApiV1UsersMePutResponse =
  UpdateUserMeApiV1UsersMePutResponses[keyof UpdateUserMeApiV1UsersMePutResponses];

export type ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostData = {
  /**
   * Busy Times
   */
  body: Array<BusyTime>;
  path?: never;
  query: {
    /**
     * Wake Up Time
     */
    wake_up_time: string;
    /**
     * Sleep Time
     */
    sleep_time: string;
  };
  url: '/api/v1/users/me/validate-busy-times';
};

export type ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostError =
  ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostErrors[keyof ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostErrors];

export type ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostResponses = {
  /**
   * Successful Response
   */
  200: BusyTimeValidationResult;
};

export type ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostResponse =
  ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostResponses[keyof ValidateBusyTimesApiV1UsersMeValidateBusyTimesPostResponses];

export type ReadUserTargetsApiV1UsersMeTargetsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/me/targets';
};

export type ReadUserTargetsApiV1UsersMeTargetsGetResponses = {
  /**
   * Successful Response
   */
  200: DriOutput;
};

export type ReadUserTargetsApiV1UsersMeTargetsGetResponse =
  ReadUserTargetsApiV1UsersMeTargetsGetResponses[keyof ReadUserTargetsApiV1UsersMeTargetsGetResponses];

export type GetScheduleItemsApiV1SchedulesGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Start Date
     *
     * Start of the date range (inclusive)
     */
    start_date: string;
    /**
     * End Date
     *
     * End of the date range (inclusive)
     */
    end_date: string;
  };
  url: '/api/v1/schedules';
};

export type GetScheduleItemsApiV1SchedulesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetScheduleItemsApiV1SchedulesGetError =
  GetScheduleItemsApiV1SchedulesGetErrors[keyof GetScheduleItemsApiV1SchedulesGetErrors];

export type GetScheduleItemsApiV1SchedulesGetResponses = {
  /**
   * Response Get Schedule Items Api V1 Schedules Get
   *
   * Successful Response
   */
  200: Array<ScheduleItemRead>;
};

export type GetScheduleItemsApiV1SchedulesGetResponse =
  GetScheduleItemsApiV1SchedulesGetResponses[keyof GetScheduleItemsApiV1SchedulesGetResponses];

export type CreateScheduleItemApiV1SchedulesPostData = {
  body: ScheduleItemCreate;
  path?: never;
  query?: never;
  url: '/api/v1/schedules';
};

export type CreateScheduleItemApiV1SchedulesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateScheduleItemApiV1SchedulesPostError =
  CreateScheduleItemApiV1SchedulesPostErrors[keyof CreateScheduleItemApiV1SchedulesPostErrors];

export type CreateScheduleItemApiV1SchedulesPostResponses = {
  /**
   * Successful Response
   */
  200: ScheduleItemRead;
};

export type CreateScheduleItemApiV1SchedulesPostResponse =
  CreateScheduleItemApiV1SchedulesPostResponses[keyof CreateScheduleItemApiV1SchedulesPostResponses];

export type DeleteScheduleItemApiV1SchedulesItemIdDeleteData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: number;
  };
  query?: never;
  url: '/api/v1/schedules/{item_id}';
};

export type DeleteScheduleItemApiV1SchedulesItemIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteScheduleItemApiV1SchedulesItemIdDeleteError =
  DeleteScheduleItemApiV1SchedulesItemIdDeleteErrors[keyof DeleteScheduleItemApiV1SchedulesItemIdDeleteErrors];

export type DeleteScheduleItemApiV1SchedulesItemIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteScheduleItemApiV1SchedulesItemIdDeleteResponse =
  DeleteScheduleItemApiV1SchedulesItemIdDeleteResponses[keyof DeleteScheduleItemApiV1SchedulesItemIdDeleteResponses];

export type UpdateScheduleItemApiV1SchedulesItemIdPutData = {
  body: ScheduleItemUpdate;
  path: {
    /**
     * Item Id
     */
    item_id: number;
  };
  query?: never;
  url: '/api/v1/schedules/{item_id}';
};

export type UpdateScheduleItemApiV1SchedulesItemIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateScheduleItemApiV1SchedulesItemIdPutError =
  UpdateScheduleItemApiV1SchedulesItemIdPutErrors[keyof UpdateScheduleItemApiV1SchedulesItemIdPutErrors];

export type UpdateScheduleItemApiV1SchedulesItemIdPutResponses = {
  /**
   * Successful Response
   */
  200: ScheduleItemRead;
};

export type UpdateScheduleItemApiV1SchedulesItemIdPutResponse =
  UpdateScheduleItemApiV1SchedulesItemIdPutResponses[keyof UpdateScheduleItemApiV1SchedulesItemIdPutResponses];

export type GenerateMealPlanApiV1MealPlansGeneratePostData = {
  body?: never;
  path?: never;
  query?: {
    day?: Day;
  };
  url: '/api/v1/meal-plans/generate';
};

export type GenerateMealPlanApiV1MealPlansGeneratePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GenerateMealPlanApiV1MealPlansGeneratePostError =
  GenerateMealPlanApiV1MealPlansGeneratePostErrors[keyof GenerateMealPlanApiV1MealPlansGeneratePostErrors];

export type GenerateMealPlanApiV1MealPlansGeneratePostResponses = {
  /**
   * Successful Response
   */
  200: DailyMealPlanOutput;
};

export type GenerateMealPlanApiV1MealPlansGeneratePostResponse =
  GenerateMealPlanApiV1MealPlansGeneratePostResponses[keyof GenerateMealPlanApiV1MealPlansGeneratePostResponses];

export type GenerateWeekPlanApiV1MealPlansGenerateWeekPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/meal-plans/generate-week';
};

export type GenerateWeekPlanApiV1MealPlansGenerateWeekPostResponses = {
  /**
   * Successful Response
   */
  200: WeeklyMealPlanOutput;
};

export type GenerateWeekPlanApiV1MealPlansGenerateWeekPostResponse =
  GenerateWeekPlanApiV1MealPlansGenerateWeekPostResponses[keyof GenerateWeekPlanApiV1MealPlansGenerateWeekPostResponses];

export type SaveMealPlanApiV1MealPlansSavePostData = {
  body: SaveMealPlanRequest;
  path?: never;
  query?: never;
  url: '/api/v1/meal-plans/save';
};

export type SaveMealPlanApiV1MealPlansSavePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SaveMealPlanApiV1MealPlansSavePostError =
  SaveMealPlanApiV1MealPlansSavePostErrors[keyof SaveMealPlanApiV1MealPlansSavePostErrors];

export type SaveMealPlanApiV1MealPlansSavePostResponses = {
  /**
   * Successful Response
   */
  200: SavedMealPlanResponse;
};

export type SaveMealPlanApiV1MealPlansSavePostResponse =
  SaveMealPlanApiV1MealPlansSavePostResponses[keyof SaveMealPlanApiV1MealPlansSavePostResponses];

export type GetWeekPlanApiV1MealPlansWeekGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Week Start Date
     *
     * Monday of the week to fetch
     */
    week_start_date: string;
  };
  url: '/api/v1/meal-plans/week';
};

export type GetWeekPlanApiV1MealPlansWeekGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWeekPlanApiV1MealPlansWeekGetError =
  GetWeekPlanApiV1MealPlansWeekGetErrors[keyof GetWeekPlanApiV1MealPlansWeekGetErrors];

export type GetWeekPlanApiV1MealPlansWeekGetResponses = {
  /**
   * Response Get Week Plan Api V1 Meal Plans Week Get
   *
   * Successful Response
   */
  200: SavedMealPlanResponse | null;
};

export type GetWeekPlanApiV1MealPlansWeekGetResponse =
  GetWeekPlanApiV1MealPlansWeekGetResponses[keyof GetWeekPlanApiV1MealPlansWeekGetResponses];

export type GetPlannedWeeksApiV1MealPlansPlannedWeeksGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/meal-plans/planned-weeks';
};

export type GetPlannedWeeksApiV1MealPlansPlannedWeeksGetResponses = {
  /**
   * Response Get Planned Weeks Api V1 Meal Plans Planned Weeks Get
   *
   * Successful Response
   */
  200: Array<string>;
};

export type GetPlannedWeeksApiV1MealPlansPlannedWeeksGetResponse =
  GetPlannedWeeksApiV1MealPlansPlannedWeeksGetResponses[keyof GetPlannedWeeksApiV1MealPlansPlannedWeeksGetResponses];

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
