// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ActivityLevel
 */
export type ActivityLevel = 'sedentary' | 'light' | 'moderate' | 'active' | 'very_active';

/**
 * Allergy
 */
export type Allergy =
  | 'Dairy'
  | 'Egg'
  | 'Gluten'
  | 'Grain'
  | 'Peanut'
  | 'Seafood'
  | 'Sesame'
  | 'Shellfish'
  | 'Soy'
  | 'Sulfite'
  | 'Tree Nut'
  | 'Wheat';

/**
 * Cuisine
 */
export type Cuisine =
  | 'African'
  | 'Asian'
  | 'American'
  | 'British'
  | 'Cajun'
  | 'Caribbean'
  | 'Chinese'
  | 'Eastern European'
  | 'European'
  | 'French'
  | 'German'
  | 'Greek'
  | 'Indian'
  | 'Irish'
  | 'Italian'
  | 'Japanese'
  | 'Jewish'
  | 'Korean'
  | 'Latin American'
  | 'Mediterranean'
  | 'Mexican'
  | 'Middle Eastern'
  | 'Nordic'
  | 'Southern'
  | 'Spanish'
  | 'Thai'
  | 'Vietnamese';

/**
 * DRIOutput
 */
export type DriOutput = {
  calories: NutrientRange;
  protein: NutrientRange;
  carbohydrates: NutrientRange;
  fat: NutrientRange;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * NutrientRange
 */
export type NutrientRange = {
  /**
   * Min
   */
  min: number;
  /**
   * Target
   */
  target: number;
  /**
   * Max
   */
  max: number;
  /**
   * Unit
   */
  unit?: string;
};

/**
 * PregnancyStatus
 */
export type PregnancyStatus =
  | 'not_pregnant'
  | 'pregnant'
  | 'exclusively_breastfeeding'
  | 'partially_breastfeeding';

/**
 * Sex
 */
export type Sex = 'male' | 'female';

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Age
   */
  age: number;
  /**
   * Weight
   */
  weight: number;
  /**
   * Height
   */
  height: number;
  /**
   * Is Metric
   */
  is_metric: boolean;
  gender: Sex;
  activity_level: ActivityLevel;
  pregnancy_status?: PregnancyStatus;
  /**
   * Allergies
   */
  allergies?: Array<Allergy>;
  /**
   * Include Cuisine
   */
  include_cuisine?: Array<Cuisine>;
  /**
   * Exclude Cuisine
   */
  exclude_cuisine?: Array<Cuisine>;
  /**
   * Is Gluten Free
   */
  is_gluten_free?: boolean;
  /**
   * Is Ketogenic
   */
  is_ketogenic?: boolean;
  /**
   * Is Vegetarian
   */
  is_vegetarian?: boolean;
  /**
   * Is Vegan
   */
  is_vegan?: boolean;
  /**
   * Is Pescatarian
   */
  is_pescatarian?: boolean;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Email
   */
  email: string;
  /**
   * Age
   */
  age: number;
  /**
   * Weight
   */
  weight: number;
  /**
   * Height
   */
  height: number;
  /**
   * Is Metric
   */
  is_metric: boolean;
  gender: Sex;
  activity_level: ActivityLevel;
  pregnancy_status?: PregnancyStatus;
  /**
   * Allergies
   */
  allergies?: Array<Allergy>;
  /**
   * Include Cuisine
   */
  include_cuisine?: Array<Cuisine>;
  /**
   * Exclude Cuisine
   */
  exclude_cuisine?: Array<Cuisine>;
  /**
   * Is Gluten Free
   */
  is_gluten_free?: boolean;
  /**
   * Is Ketogenic
   */
  is_ketogenic?: boolean;
  /**
   * Is Vegetarian
   */
  is_vegetarian?: boolean;
  /**
   * Is Vegan
   */
  is_vegan?: boolean;
  /**
   * Is Pescatarian
   */
  is_pescatarian?: boolean;
  /**
   * Id
   */
  id: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Email
   */
  email?: string | null;
  /**
   * Age
   */
  age?: number | null;
  /**
   * Weight
   */
  weight?: number | null;
  /**
   * Height
   */
  height?: number | null;
  /**
   * Is Metric
   */
  is_metric?: boolean | null;
  gender?: Sex | null;
  activity_level?: ActivityLevel | null;
  pregnancy_status?: PregnancyStatus | null;
  /**
   * Allergies
   */
  allergies?: Array<Allergy> | null;
  /**
   * Include Cuisine
   */
  include_cuisine?: Array<Cuisine> | null;
  /**
   * Exclude Cuisine
   */
  exclude_cuisine?: Array<Cuisine> | null;
  /**
   * Is Gluten Free
   */
  is_gluten_free?: boolean | null;
  /**
   * Is Ketogenic
   */
  is_ketogenic?: boolean | null;
  /**
   * Is Vegetarian
   */
  is_vegetarian?: boolean | null;
  /**
   * Is Vegan
   */
  is_vegan?: boolean | null;
  /**
   * Is Pescatarian
   */
  is_pescatarian?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type CreateUserApiV1UsersPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: '/api/v1/users';
};

export type CreateUserApiV1UsersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserApiV1UsersPostError =
  CreateUserApiV1UsersPostErrors[keyof CreateUserApiV1UsersPostErrors];

export type CreateUserApiV1UsersPostResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type CreateUserApiV1UsersPostResponse =
  CreateUserApiV1UsersPostResponses[keyof CreateUserApiV1UsersPostResponses];

export type ReadUserMeApiV1UsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/me';
};

export type ReadUserMeApiV1UsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type ReadUserMeApiV1UsersMeGetResponse =
  ReadUserMeApiV1UsersMeGetResponses[keyof ReadUserMeApiV1UsersMeGetResponses];

export type UpdateUserMeApiV1UsersMePutData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: '/api/v1/users/me';
};

export type UpdateUserMeApiV1UsersMePutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserMeApiV1UsersMePutError =
  UpdateUserMeApiV1UsersMePutErrors[keyof UpdateUserMeApiV1UsersMePutErrors];

export type UpdateUserMeApiV1UsersMePutResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UpdateUserMeApiV1UsersMePutResponse =
  UpdateUserMeApiV1UsersMePutResponses[keyof UpdateUserMeApiV1UsersMePutResponses];

export type ReadUserTargetsApiV1UsersMeTargetsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/me/targets';
};

export type ReadUserTargetsApiV1UsersMeTargetsGetResponses = {
  /**
   * Successful Response
   */
  200: DriOutput;
};

export type ReadUserTargetsApiV1UsersMeTargetsGetResponse =
  ReadUserTargetsApiV1UsersMeTargetsGetResponses[keyof ReadUserTargetsApiV1UsersMeTargetsGetResponses];

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
