// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ActivityLevel
 */
export type ActivityLevel = 'sedentary' | 'light' | 'moderate' | 'active' | 'very_active';

/**
 * ActivityType
 */
export type ActivityType = 'meal' | 'sleep' | 'work' | 'exercise' | 'leisure' | 'other';

/**
 * Allergy
 */
export type Allergy =
  | 'Dairy'
  | 'Egg'
  | 'Gluten'
  | 'Grain'
  | 'Peanut'
  | 'Seafood'
  | 'Sesame'
  | 'Shellfish'
  | 'Soy'
  | 'Sulfite'
  | 'Tree Nut'
  | 'Wheat';

/**
 * ArchivedGoalCreate
 *
 * Matches the ArchivedGoalSummary type in the frontend.
 * The id is a stable string derived from startDate_targetDate.
 */
export type ArchivedGoalCreate = {
  /**
   * Id
   */
  id: string;
  /**
   * Start Date
   */
  start_date: string;
  /**
   * Target Date
   */
  target_date: string;
  /**
   * Start Weight Kg
   */
  start_weight_kg: number;
  /**
   * Target Weight Kg
   */
  target_weight_kg: number;
  /**
   * End Date
   */
  end_date: string;
  /**
   * Final Weight Kg
   */
  final_weight_kg?: number | null;
  /**
   * Weight Change Kg
   */
  weight_change_kg?: number | null;
  /**
   * Archived At
   */
  archived_at: string;
};

/**
 * ArchivedGoalRead
 */
export type ArchivedGoalRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Start Date
   */
  start_date: string;
  /**
   * Target Date
   */
  target_date: string;
  /**
   * Start Weight Kg
   */
  start_weight_kg: number;
  /**
   * Target Weight Kg
   */
  target_weight_kg: number;
  /**
   * End Date
   */
  end_date: string;
  /**
   * Final Weight Kg
   */
  final_weight_kg?: number | null;
  /**
   * Weight Change Kg
   */
  weight_change_kg?: number | null;
  /**
   * Archived At
   */
  archived_at: string;
};

/**
 * BusyTime
 */
export type BusyTime = {
  day?: Day;
  /**
   * Start
   */
  start?: string;
  /**
   * End
   */
  end?: string;
};

/**
 * Cuisine
 */
export type Cuisine =
  | 'African'
  | 'Asian'
  | 'American'
  | 'British'
  | 'Cajun'
  | 'Caribbean'
  | 'Chinese'
  | 'Eastern European'
  | 'European'
  | 'French'
  | 'German'
  | 'Greek'
  | 'Indian'
  | 'Irish'
  | 'Italian'
  | 'Japanese'
  | 'Jewish'
  | 'Korean'
  | 'Latin American'
  | 'Mediterranean'
  | 'Mexican'
  | 'Middle Eastern'
  | 'Nordic'
  | 'Southern'
  | 'Spanish'
  | 'Thai'
  | 'Vietnamese';

/**
 * CustomMealInput
 */
export type CustomMealInput = {
  /**
   * Title
   */
  title: string;
  /**
   * Calories
   */
  calories: number;
  /**
   * Protein
   */
  protein: number;
  /**
   * Carbohydrates
   */
  carbohydrates: number;
  /**
   * Fat
   */
  fat: number;
};

/**
 * DRIOutput
 */
export type DriOutput = {
  calories: NutrientRange;
  protein: NutrientRange;
  carbohydrates: NutrientRange;
  fat: NutrientRange;
};

/**
 * Day
 */
export type Day =
  | 'Monday'
  | 'Tuesday'
  | 'Wednesday'
  | 'Thursday'
  | 'Friday'
  | 'Saturday'
  | 'Sunday';

/**
 * ExerciseCategory
 */
export type ExerciseCategory = 'Cardio' | 'Weight Lifting';

/**
 * GoogleCalendarDisconnectResult
 */
export type GoogleCalendarDisconnectResult = {
  /**
   * Removed Busy Blocks
   */
  removed_busy_blocks: number;
};

/**
 * GoogleCalendarStatus
 */
export type GoogleCalendarStatus = {
  /**
   * Connected
   */
  connected: boolean;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Last Synced At
   */
  last_synced_at?: string | null;
  /**
   * Sync Status
   */
  sync_status?: string | null;
  /**
   * Needs Reconnect
   */
  needs_reconnect?: boolean;
};

/**
 * GoogleCalendarSyncResult
 */
export type GoogleCalendarSyncResult = {
  /**
   * Synced Count
   */
  synced_count: number;
  /**
   * Sync Batch Id
   */
  sync_batch_id: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * MealRead
 */
export type MealRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Recipe Id
   */
  recipe_id?: string | null;
  /**
   * Title
   */
  title: string;
  /**
   * Image Url
   */
  image_url?: string | null;
  /**
   * Source Url
   */
  source_url?: string | null;
  /**
   * Calories
   */
  calories: number;
  /**
   * Protein
   */
  protein: number;
  /**
   * Carbohydrates
   */
  carbohydrates: number;
  /**
   * Fat
   */
  fat: number;
  /**
   * Prep Time Minutes
   */
  prep_time_minutes?: number | null;
  /**
   * Ingredients
   */
  ingredients?: Array<string>;
  /**
   * Tags
   */
  tags?: Array<string>;
  /**
   * Is Custom
   */
  is_custom?: boolean;
};

/**
 * NutrientRange
 */
export type NutrientRange = {
  /**
   * Min
   */
  min: number;
  /**
   * Target
   */
  target: number;
  /**
   * Max
   */
  max: number;
  /**
   * Unit
   */
  unit?: string;
};

/**
 * PregnancyStatus
 */
export type PregnancyStatus =
  | 'not_pregnant'
  | 'pregnant'
  | 'exclusively_breastfeeding'
  | 'partially_breastfeeding';

/**
 * ScheduleItemCreate
 */
export type ScheduleItemCreate = {
  /**
   * Date
   */
  date: string;
  activity_type: ActivityType;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Is Completed
   */
  is_completed?: boolean;
  exercise_category?: ExerciseCategory | null;
  /**
   * Exercise Calorie Burn
   */
  exercise_calorie_burn?: number;
  /**
   * Exercise Muscle Gain
   */
  exercise_muscle_gain?: number;
  /**
   * Meal Id
   */
  meal_id?: number | null;
  custom_meal?: CustomMealInput | null;
};

/**
 * ScheduleItemRead
 */
export type ScheduleItemRead = {
  /**
   * Date
   */
  date: string;
  activity_type: ActivityType;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Is Completed
   */
  is_completed?: boolean;
  exercise_category?: ExerciseCategory | null;
  /**
   * Exercise Calorie Burn
   */
  exercise_calorie_burn?: number;
  /**
   * Exercise Muscle Gain
   */
  exercise_muscle_gain?: number;
  /**
   * Id
   */
  id: number;
  /**
   * User Id
   */
  user_id: string;
  /**
   * Meal Id
   */
  meal_id?: number | null;
  /**
   * Meal Type
   */
  meal_type?: string | null;
  /**
   * Source Schedule Item Id
   */
  source_schedule_item_id?: number | null;
  /**
   * Source Type
   */
  source_type?: string;
  /**
   * Source Calendar Id
   */
  source_calendar_id?: string | null;
  meal?: MealRead | null;
  /**
   * Alternatives
   */
  alternatives?: Array<MealRead>;
};

/**
 * ScheduleItemUpdate
 */
export type ScheduleItemUpdate = {
  /**
   * Date
   */
  date?: string | null;
  activity_type?: ActivityType | null;
  /**
   * Duration Minutes
   */
  duration_minutes?: number | null;
  /**
   * Is Completed
   */
  is_completed?: boolean | null;
  exercise_category?: ExerciseCategory | null;
};

/**
 * Sex
 */
export type Sex = 'male' | 'female';

/**
 * SwapMealRequest
 */
export type SwapMealRequest = {
  /**
   * Meal Id
   */
  meal_id: number;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Age
   */
  age: number;
  /**
   * Weight
   */
  weight: number;
  /**
   * Height
   */
  height: number;
  /**
   * Show Imperial
   */
  show_imperial: boolean;
  gender: Sex;
  activity_level: ActivityLevel;
  pregnancy_status?: PregnancyStatus;
  /**
   * Target Weight
   */
  target_weight?: number | null;
  /**
   * Target Date
   */
  target_date?: string | null;
  /**
   * Goal Start Date
   */
  goal_start_date?: string | null;
  /**
   * Goal Start Weight Kg
   */
  goal_start_weight_kg?: number | null;
  /**
   * Wake Up Time
   */
  wake_up_time?: string;
  /**
   * Sleep Time
   */
  sleep_time?: string;
  /**
   * Busy Times
   */
  busy_times?: Array<BusyTime>;
  /**
   * Allergies
   */
  allergies?: Array<Allergy>;
  /**
   * Include Cuisine
   */
  include_cuisine?: Array<Cuisine>;
  /**
   * Exclude Cuisine
   */
  exclude_cuisine?: Array<Cuisine>;
  /**
   * Is Gluten Free
   */
  is_gluten_free?: boolean;
  /**
   * Is Ketogenic
   */
  is_ketogenic?: boolean;
  /**
   * Is Vegetarian
   */
  is_vegetarian?: boolean;
  /**
   * Is Vegan
   */
  is_vegan?: boolean;
  /**
   * Is Pescatarian
   */
  is_pescatarian?: boolean;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Email
   */
  email: string;
  /**
   * Age
   */
  age: number;
  /**
   * Weight
   */
  weight: number;
  /**
   * Height
   */
  height: number;
  /**
   * Show Imperial
   */
  show_imperial: boolean;
  gender: Sex;
  activity_level: ActivityLevel;
  pregnancy_status?: PregnancyStatus;
  /**
   * Target Weight
   */
  target_weight?: number | null;
  /**
   * Target Date
   */
  target_date?: string | null;
  /**
   * Goal Start Date
   */
  goal_start_date?: string | null;
  /**
   * Goal Start Weight Kg
   */
  goal_start_weight_kg?: number | null;
  /**
   * Wake Up Time
   */
  wake_up_time?: string;
  /**
   * Sleep Time
   */
  sleep_time?: string;
  /**
   * Busy Times
   */
  busy_times?: Array<BusyTime>;
  /**
   * Allergies
   */
  allergies?: Array<Allergy>;
  /**
   * Include Cuisine
   */
  include_cuisine?: Array<Cuisine>;
  /**
   * Exclude Cuisine
   */
  exclude_cuisine?: Array<Cuisine>;
  /**
   * Is Gluten Free
   */
  is_gluten_free?: boolean;
  /**
   * Is Ketogenic
   */
  is_ketogenic?: boolean;
  /**
   * Is Vegetarian
   */
  is_vegetarian?: boolean;
  /**
   * Is Vegan
   */
  is_vegan?: boolean;
  /**
   * Is Pescatarian
   */
  is_pescatarian?: boolean;
  /**
   * Id
   */
  id: string;
  /**
   * Schedules
   */
  schedules?: Array<unknown>;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Email
   */
  email?: string | null;
  /**
   * Age
   */
  age?: number | null;
  /**
   * Weight
   */
  weight?: number | null;
  /**
   * Height
   */
  height?: number | null;
  /**
   * Show Imperial
   */
  show_imperial?: boolean | null;
  gender?: Sex | null;
  activity_level?: ActivityLevel | null;
  pregnancy_status?: PregnancyStatus | null;
  /**
   * Target Weight
   */
  target_weight?: number | null;
  /**
   * Target Date
   */
  target_date?: string | null;
  /**
   * Goal Start Date
   */
  goal_start_date?: string | null;
  /**
   * Goal Start Weight Kg
   */
  goal_start_weight_kg?: number | null;
  /**
   * Wake Up Time
   */
  wake_up_time?: string | null;
  /**
   * Sleep Time
   */
  sleep_time?: string | null;
  /**
   * Busy Times
   */
  busy_times?: Array<BusyTime> | null;
  /**
   * Allergies
   */
  allergies?: Array<Allergy> | null;
  /**
   * Include Cuisine
   */
  include_cuisine?: Array<Cuisine> | null;
  /**
   * Exclude Cuisine
   */
  exclude_cuisine?: Array<Cuisine> | null;
  /**
   * Is Gluten Free
   */
  is_gluten_free?: boolean | null;
  /**
   * Is Ketogenic
   */
  is_ketogenic?: boolean | null;
  /**
   * Is Vegetarian
   */
  is_vegetarian?: boolean | null;
  /**
   * Is Vegan
   */
  is_vegan?: boolean | null;
  /**
   * Is Pescatarian
   */
  is_pescatarian?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * WeightLogEntryCreate
 */
export type WeightLogEntryCreate = {
  /**
   * Date
   */
  date: string;
  /**
   * Weight Kg
   */
  weight_kg: number;
  /**
   * Source
   */
  source?: 'prompt' | 'manual' | 'baseline';
};

/**
 * WeightLogEntryRead
 */
export type WeightLogEntryRead = {
  /**
   * Date
   */
  date: string;
  /**
   * Weight Kg
   */
  weight_kg: number;
  /**
   * Source
   */
  source: string;
};

export type CreateUserApiV1UsersPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: '/api/v1/users';
};

export type CreateUserApiV1UsersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserApiV1UsersPostError =
  CreateUserApiV1UsersPostErrors[keyof CreateUserApiV1UsersPostErrors];

export type CreateUserApiV1UsersPostResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type CreateUserApiV1UsersPostResponse =
  CreateUserApiV1UsersPostResponses[keyof CreateUserApiV1UsersPostResponses];

export type ReadUserMeApiV1UsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/me';
};

export type ReadUserMeApiV1UsersMeGetErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type ReadUserMeApiV1UsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type ReadUserMeApiV1UsersMeGetResponse =
  ReadUserMeApiV1UsersMeGetResponses[keyof ReadUserMeApiV1UsersMeGetResponses];

export type UpdateUserMeApiV1UsersMePutData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: '/api/v1/users/me';
};

export type UpdateUserMeApiV1UsersMePutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserMeApiV1UsersMePutError =
  UpdateUserMeApiV1UsersMePutErrors[keyof UpdateUserMeApiV1UsersMePutErrors];

export type UpdateUserMeApiV1UsersMePutResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UpdateUserMeApiV1UsersMePutResponse =
  UpdateUserMeApiV1UsersMePutResponses[keyof UpdateUserMeApiV1UsersMePutResponses];

export type ReadUserTargetsApiV1UsersMeTargetsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/me/targets';
};

export type ReadUserTargetsApiV1UsersMeTargetsGetResponses = {
  /**
   * Successful Response
   */
  200: DriOutput;
};

export type ReadUserTargetsApiV1UsersMeTargetsGetResponse =
  ReadUserTargetsApiV1UsersMeTargetsGetResponses[keyof ReadUserTargetsApiV1UsersMeTargetsGetResponses];

export type GetWeekScheduleApiV1SchedulesWeekGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Week Start Date
     *
     * Monday of the week (YYYY-MM-DD)
     */
    week_start_date: string;
  };
  url: '/api/v1/schedules/week';
};

export type GetWeekScheduleApiV1SchedulesWeekGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWeekScheduleApiV1SchedulesWeekGetError =
  GetWeekScheduleApiV1SchedulesWeekGetErrors[keyof GetWeekScheduleApiV1SchedulesWeekGetErrors];

export type GetWeekScheduleApiV1SchedulesWeekGetResponses = {
  /**
   * Response Get Week Schedule Api V1 Schedules Week Get
   *
   * Successful Response
   */
  200: Array<ScheduleItemRead>;
};

export type GetWeekScheduleApiV1SchedulesWeekGetResponse =
  GetWeekScheduleApiV1SchedulesWeekGetResponses[keyof GetWeekScheduleApiV1SchedulesWeekGetResponses];

export type GetScheduleItemsApiV1SchedulesGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
  };
  url: '/api/v1/schedules';
};

export type GetScheduleItemsApiV1SchedulesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetScheduleItemsApiV1SchedulesGetError =
  GetScheduleItemsApiV1SchedulesGetErrors[keyof GetScheduleItemsApiV1SchedulesGetErrors];

export type GetScheduleItemsApiV1SchedulesGetResponses = {
  /**
   * Response Get Schedule Items Api V1 Schedules Get
   *
   * Successful Response
   */
  200: Array<ScheduleItemRead>;
};

export type GetScheduleItemsApiV1SchedulesGetResponse =
  GetScheduleItemsApiV1SchedulesGetResponses[keyof GetScheduleItemsApiV1SchedulesGetResponses];

export type CreateScheduleItemApiV1SchedulesPostData = {
  body: ScheduleItemCreate;
  path?: never;
  query?: never;
  url: '/api/v1/schedules';
};

export type CreateScheduleItemApiV1SchedulesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateScheduleItemApiV1SchedulesPostError =
  CreateScheduleItemApiV1SchedulesPostErrors[keyof CreateScheduleItemApiV1SchedulesPostErrors];

export type CreateScheduleItemApiV1SchedulesPostResponses = {
  /**
   * Successful Response
   */
  200: ScheduleItemRead;
};

export type CreateScheduleItemApiV1SchedulesPostResponse =
  CreateScheduleItemApiV1SchedulesPostResponses[keyof CreateScheduleItemApiV1SchedulesPostResponses];

export type DeleteScheduleItemApiV1SchedulesItemIdDeleteData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: number;
  };
  query?: never;
  url: '/api/v1/schedules/{item_id}';
};

export type DeleteScheduleItemApiV1SchedulesItemIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteScheduleItemApiV1SchedulesItemIdDeleteError =
  DeleteScheduleItemApiV1SchedulesItemIdDeleteErrors[keyof DeleteScheduleItemApiV1SchedulesItemIdDeleteErrors];

export type DeleteScheduleItemApiV1SchedulesItemIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteScheduleItemApiV1SchedulesItemIdDeleteResponse =
  DeleteScheduleItemApiV1SchedulesItemIdDeleteResponses[keyof DeleteScheduleItemApiV1SchedulesItemIdDeleteResponses];

export type UpdateScheduleItemApiV1SchedulesItemIdPutData = {
  body: ScheduleItemUpdate;
  path: {
    /**
     * Item Id
     */
    item_id: number;
  };
  query?: never;
  url: '/api/v1/schedules/{item_id}';
};

export type UpdateScheduleItemApiV1SchedulesItemIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateScheduleItemApiV1SchedulesItemIdPutError =
  UpdateScheduleItemApiV1SchedulesItemIdPutErrors[keyof UpdateScheduleItemApiV1SchedulesItemIdPutErrors];

export type UpdateScheduleItemApiV1SchedulesItemIdPutResponses = {
  /**
   * Successful Response
   */
  200: ScheduleItemRead;
};

export type UpdateScheduleItemApiV1SchedulesItemIdPutResponse =
  UpdateScheduleItemApiV1SchedulesItemIdPutResponses[keyof UpdateScheduleItemApiV1SchedulesItemIdPutResponses];

export type SwapScheduleItemMealApiV1SchedulesItemIdSwapPostData = {
  body: SwapMealRequest;
  path: {
    /**
     * Item Id
     */
    item_id: number;
  };
  query?: never;
  url: '/api/v1/schedules/{item_id}/swap';
};

export type SwapScheduleItemMealApiV1SchedulesItemIdSwapPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SwapScheduleItemMealApiV1SchedulesItemIdSwapPostError =
  SwapScheduleItemMealApiV1SchedulesItemIdSwapPostErrors[keyof SwapScheduleItemMealApiV1SchedulesItemIdSwapPostErrors];

export type SwapScheduleItemMealApiV1SchedulesItemIdSwapPostResponses = {
  /**
   * Successful Response
   */
  200: ScheduleItemRead;
};

export type SwapScheduleItemMealApiV1SchedulesItemIdSwapPostResponse =
  SwapScheduleItemMealApiV1SchedulesItemIdSwapPostResponses[keyof SwapScheduleItemMealApiV1SchedulesItemIdSwapPostResponses];

export type GenerateWeekPlanApiV1MealPlansGenerateWeekPostData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Week Start Date
     *
     * Monday of the week to generate (YYYY-MM-DD)
     */
    week_start_date: string;
  };
  url: '/api/v1/meal-plans/generate-week';
};

export type GenerateWeekPlanApiV1MealPlansGenerateWeekPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GenerateWeekPlanApiV1MealPlansGenerateWeekPostError =
  GenerateWeekPlanApiV1MealPlansGenerateWeekPostErrors[keyof GenerateWeekPlanApiV1MealPlansGenerateWeekPostErrors];

export type GenerateWeekPlanApiV1MealPlansGenerateWeekPostResponses = {
  /**
   * Response Generate Week Plan Api V1 Meal Plans Generate Week Post
   *
   * Successful Response
   */
  200: Array<ScheduleItemRead>;
};

export type GenerateWeekPlanApiV1MealPlansGenerateWeekPostResponse =
  GenerateWeekPlanApiV1MealPlansGenerateWeekPostResponses[keyof GenerateWeekPlanApiV1MealPlansGenerateWeekPostResponses];

export type GetPlannedWeeksApiV1MealPlansPlannedWeeksGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/meal-plans/planned-weeks';
};

export type GetPlannedWeeksApiV1MealPlansPlannedWeeksGetResponses = {
  /**
   * Response Get Planned Weeks Api V1 Meal Plans Planned Weeks Get
   *
   * Successful Response
   */
  200: Array<string>;
};

export type GetPlannedWeeksApiV1MealPlansPlannedWeeksGetResponse =
  GetPlannedWeeksApiV1MealPlansPlannedWeeksGetResponses[keyof GetPlannedWeeksApiV1MealPlansPlannedWeeksGetResponses];

export type GetWeightLogApiV1UsersMeProgressWeightLogGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/me/progress/weight-log';
};

export type GetWeightLogApiV1UsersMeProgressWeightLogGetResponses = {
  /**
   * Response Get Weight Log Api V1 Users Me Progress Weight Log Get
   *
   * Successful Response
   */
  200: Array<WeightLogEntryRead>;
};

export type GetWeightLogApiV1UsersMeProgressWeightLogGetResponse =
  GetWeightLogApiV1UsersMeProgressWeightLogGetResponses[keyof GetWeightLogApiV1UsersMeProgressWeightLogGetResponses];

export type UpsertWeightEntryApiV1UsersMeProgressWeightLogPostData = {
  body: WeightLogEntryCreate;
  path?: never;
  query?: never;
  url: '/api/v1/users/me/progress/weight-log';
};

export type UpsertWeightEntryApiV1UsersMeProgressWeightLogPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpsertWeightEntryApiV1UsersMeProgressWeightLogPostError =
  UpsertWeightEntryApiV1UsersMeProgressWeightLogPostErrors[keyof UpsertWeightEntryApiV1UsersMeProgressWeightLogPostErrors];

export type UpsertWeightEntryApiV1UsersMeProgressWeightLogPostResponses = {
  /**
   * Successful Response
   */
  200: WeightLogEntryRead;
};

export type UpsertWeightEntryApiV1UsersMeProgressWeightLogPostResponse =
  UpsertWeightEntryApiV1UsersMeProgressWeightLogPostResponses[keyof UpsertWeightEntryApiV1UsersMeProgressWeightLogPostResponses];

export type DeleteWeightEntryApiV1UsersMeProgressWeightLogEntryDateDeleteData = {
  body?: never;
  path: {
    /**
     * Entry Date
     */
    entry_date: string;
  };
  query?: never;
  url: '/api/v1/users/me/progress/weight-log/{entry_date}';
};

export type DeleteWeightEntryApiV1UsersMeProgressWeightLogEntryDateDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteWeightEntryApiV1UsersMeProgressWeightLogEntryDateDeleteError =
  DeleteWeightEntryApiV1UsersMeProgressWeightLogEntryDateDeleteErrors[keyof DeleteWeightEntryApiV1UsersMeProgressWeightLogEntryDateDeleteErrors];

export type DeleteWeightEntryApiV1UsersMeProgressWeightLogEntryDateDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteWeightEntryApiV1UsersMeProgressWeightLogEntryDateDeleteResponse =
  DeleteWeightEntryApiV1UsersMeProgressWeightLogEntryDateDeleteResponses[keyof DeleteWeightEntryApiV1UsersMeProgressWeightLogEntryDateDeleteResponses];

export type GetArchivedGoalsApiV1UsersMeProgressArchivedGoalsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/me/progress/archived-goals';
};

export type GetArchivedGoalsApiV1UsersMeProgressArchivedGoalsGetResponses = {
  /**
   * Response Get Archived Goals Api V1 Users Me Progress Archived Goals Get
   *
   * Successful Response
   */
  200: Array<ArchivedGoalRead>;
};

export type GetArchivedGoalsApiV1UsersMeProgressArchivedGoalsGetResponse =
  GetArchivedGoalsApiV1UsersMeProgressArchivedGoalsGetResponses[keyof GetArchivedGoalsApiV1UsersMeProgressArchivedGoalsGetResponses];

export type UpsertArchivedGoalApiV1UsersMeProgressArchivedGoalsPostData = {
  body: ArchivedGoalCreate;
  path?: never;
  query?: never;
  url: '/api/v1/users/me/progress/archived-goals';
};

export type UpsertArchivedGoalApiV1UsersMeProgressArchivedGoalsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpsertArchivedGoalApiV1UsersMeProgressArchivedGoalsPostError =
  UpsertArchivedGoalApiV1UsersMeProgressArchivedGoalsPostErrors[keyof UpsertArchivedGoalApiV1UsersMeProgressArchivedGoalsPostErrors];

export type UpsertArchivedGoalApiV1UsersMeProgressArchivedGoalsPostResponses = {
  /**
   * Successful Response
   */
  200: ArchivedGoalRead;
};

export type UpsertArchivedGoalApiV1UsersMeProgressArchivedGoalsPostResponse =
  UpsertArchivedGoalApiV1UsersMeProgressArchivedGoalsPostResponses[keyof UpsertArchivedGoalApiV1UsersMeProgressArchivedGoalsPostResponses];

export type ConnectCalendarApiV1CalendarGoogleConnectPostData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Utc Offset Minutes
     *
     * User's UTC offset in minutes, e.g. -240 for EDT. Pass -new Date().getTimezoneOffset() from the client.
     */
    utc_offset_minutes?: number;
  };
  url: '/api/v1/calendar/google/connect';
};

export type ConnectCalendarApiV1CalendarGoogleConnectPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ConnectCalendarApiV1CalendarGoogleConnectPostError =
  ConnectCalendarApiV1CalendarGoogleConnectPostErrors[keyof ConnectCalendarApiV1CalendarGoogleConnectPostErrors];

export type ConnectCalendarApiV1CalendarGoogleConnectPostResponses = {
  /**
   * Successful Response
   */
  200: GoogleCalendarStatus;
};

export type ConnectCalendarApiV1CalendarGoogleConnectPostResponse =
  ConnectCalendarApiV1CalendarGoogleConnectPostResponses[keyof ConnectCalendarApiV1CalendarGoogleConnectPostResponses];

export type GetStatusApiV1CalendarGoogleStatusGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/calendar/google/status';
};

export type GetStatusApiV1CalendarGoogleStatusGetResponses = {
  /**
   * Successful Response
   */
  200: GoogleCalendarStatus;
};

export type GetStatusApiV1CalendarGoogleStatusGetResponse =
  GetStatusApiV1CalendarGoogleStatusGetResponses[keyof GetStatusApiV1CalendarGoogleStatusGetResponses];

export type SyncCalendarApiV1CalendarGoogleSyncPostData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Utc Offset Minutes
     *
     * User's UTC offset in minutes. Pass -new Date().getTimezoneOffset() from the client.
     */
    utc_offset_minutes?: number;
  };
  url: '/api/v1/calendar/google/sync';
};

export type SyncCalendarApiV1CalendarGoogleSyncPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SyncCalendarApiV1CalendarGoogleSyncPostError =
  SyncCalendarApiV1CalendarGoogleSyncPostErrors[keyof SyncCalendarApiV1CalendarGoogleSyncPostErrors];

export type SyncCalendarApiV1CalendarGoogleSyncPostResponses = {
  /**
   * Successful Response
   */
  200: GoogleCalendarSyncResult;
};

export type SyncCalendarApiV1CalendarGoogleSyncPostResponse =
  SyncCalendarApiV1CalendarGoogleSyncPostResponses[keyof SyncCalendarApiV1CalendarGoogleSyncPostResponses];

export type DisconnectCalendarApiV1CalendarGoogleDisconnectDeleteData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Remove Busy Blocks
     *
     * Also delete imported Google busy blocks from the schedule
     */
    remove_busy_blocks?: boolean;
  };
  url: '/api/v1/calendar/google/disconnect';
};

export type DisconnectCalendarApiV1CalendarGoogleDisconnectDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DisconnectCalendarApiV1CalendarGoogleDisconnectDeleteError =
  DisconnectCalendarApiV1CalendarGoogleDisconnectDeleteErrors[keyof DisconnectCalendarApiV1CalendarGoogleDisconnectDeleteErrors];

export type DisconnectCalendarApiV1CalendarGoogleDisconnectDeleteResponses = {
  /**
   * Successful Response
   */
  200: GoogleCalendarDisconnectResult;
};

export type DisconnectCalendarApiV1CalendarGoogleDisconnectDeleteResponse =
  DisconnectCalendarApiV1CalendarGoogleDisconnectDeleteResponses[keyof DisconnectCalendarApiV1CalendarGoogleDisconnectDeleteResponses];

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
